services: 
  postgres: 
    image: postgres:16
    container_name: nest-websocket-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_DB}
    ports: 
      - '${DATABASE_PORT}:5432'
    volumes:
      - pg_data:/data

volumes: 
  pg_data: